=== BlackBeltTechnology/judo-generator/hu.blackbelt.judo.generator.templates.migration/src/script-definition.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="scriptDefinition">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="sql" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name" use="required"/>
                <xs:attribute type="xs:string" name="scriptName" use="required"/>
                <xs:attribute type="xs:string" name="out" use="required"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
        <xs:element name="changeset" maxOccurs="4" minOccurs="4">
          <xs:complexType mixed="true">
            <xs:sequence>
              <xs:element name="change" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="sql" use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="name" use="required">
            	<xs:simpleType>
            		<xs:restriction base="xs:string">
            			<xs:enumeration value="changeset-full"/>
            			<xs:enumeration value="changeset-before-incremental"/>
            			<xs:enumeration value="changeset-incremental"/>
            			<xs:enumeration value="changeset-after-incremental"/>
            		</xs:restriction>
            	</xs:simpleType>
            </xs:attribute>           
            <xs:attribute type="xs:string" name="scriptName" use="required"/>
            <xs:attribute type="xs:string" name="out" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== BlackBeltTechnology/judo-generator/hu.blackbelt.judo.generator.templates.migration/src/script-definition.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE xml>
<scriptDefinition xmlns="https://rdbms.script.generator.judo.blackbelt.hu"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="./script-definition.xsd">

	<!-- Variables:
		- currentVersion - The current version which composited from project version and MD5 sum of the model.
		- previpusVersion - The previous version which is used to make delta model. The incremental version based on that.
		- dialect - The sql dialects. All variants are executed on all script
	-->


	<sql name = "create-table-full" scriptName="templates/sql/create-table-full.egl" out ="schema/sql/${currentVersion}/${dialect}/create-table-full.sql"/>
	<sql name = "create-foreignkey" scriptName="templates/sql/create-foreignkey.egl" out ="schema/sql/${currentVersion}/${dialect}/create-foreignkey.sql"/>
	<sql name = "create-not-null-constraint" scriptName="templates/sql/create-not-null-constraint.egl" out ="schema/sql/${currentVersion}/${dialect}/create-not-null-constraint.sql"/>
	<sql name = "create-unique-constraint" scriptName="templates/sql/create-unique-constraint.egl" out ="schema/sql/${currentVersion}/${dialect}/create-unique-constraint.sql"/>

	<!-- It runs when there is NO DB presented -->
	<changeset name = "changeset-full"  scriptName="templates/xml/changeset.egl" out="schema/${currentVersion}-${dialect}-schema-full.xml" >
		<change sql ="sql/${currentVersion}/${dialect}/create-table-full.sql"/>
		<change sql ="sql/${currentVersion}/${dialect}/create-foreignkey.sql"/>
		<change sql ="sql/${currentVersion}/${dialect}/create-not-null-constraint.sql"/>
		<change sql ="sql/${currentVersion}/${dialect}/create-unique-constraint.sql"/>
	</changeset>

</scriptDefinition>
